### PR TITLE
Working on professor endpoint

### PR DESCRIPTION
**Pull request by adamcee**
Work on #2 . @fravila08 thoughts / review?

Implemented:
- This
- That

WIP:
- The other On branch 2-add-professors-endpoint

### CODE REVIEW

**Comment by Bobbytx** [comment]
testing

**Comment by BDubOne** [comment]
Why is a raven like a writing desk?

**Comment by Bobbytx** [comment]
> Why is a raven like a writing desk?

idk why?

**Comment by BDubOne** [comment]
> > Why is a raven like a writing desk?
> 
> idk why?

never could understand that little tidbit from the Mad Hatter

**Pull request merged**
